### ISSUE TITLE
How to get username from a chat

### ISSUE THREAD

**Issue by NateSun97** [nickoala/telepot#297] opened 2017-09-09 06:17 UTC
Hi guys sorry for this stupid question. I'm new to Python and telepot. Just wondering how can I know the username of someone if he's chatting with my bot. Thanks

**Comment by das7pad** [comment] 2017-09-09 09:19
It is not a "stupid question" but a **lazy one** as you could have used the search first:
https://github.com/nickoala/telepot/issues?q=username

Duplicate of #286 and #278

**Closed** 2017-10-14 04:06 UTC
